### ISSUE TITLE
Access and github pages publishing

### ISSUE THREAD

**Issue by mmontone** [mmontone/Cuis-Website#1]
@jvuletich , podes darme permisos para editar 'Settings' a este repo?

 Los perdi cuando lo transferi de mi cuenta Github a Cuis-Smalltalk organization, y quisiera ver de activar Github pages.

Gracias!

**Comment by jvuletich** [comment]
Te acabo de dar derechos de admin. Decime si funciona ok.

**Comment by mmontone** [comment]
Si. Gracias!
